spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverclassname: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle9iDialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
